services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    # ELIMINA LA SECCIÓN DE PUERTOS (ports: - "5432:5432")

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8090:8000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db

volumes:
  postgres_data: