# Generated by Django 5.0.1 on 2026-09-26 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('prefijo_codigo', models.CharField(blank=True, help_text='Ej: HID para Hidráulica, VAL para Válvulas', max_length=10, verbose_name='Prefijo de Código')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='inventario_app.categoria')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Ítem')),
                ('codigo_interno', models.CharField(help_text='Se genera automáticamente si se deja vacío', max_length=50, unique=True, verbose_name='Código Interno')),
                ('numero_parte_haas', models.CharField(blank=True, help_text='Número de parte asignado por HAAS', max_length=100, verbose_name='Nº Parte HAAS')),
                ('fabricante', models.CharField(blank=True, max_length=100)),
                ('numero_serie', models.CharField(blank=True, help_text='Para herramientas o ítems únicos', max_length=100, verbose_name='Nº de Serie')),
                ('stock_actual', models.IntegerField(default=0, verbose_name='Stock Actual')),
                ('stock_minimo', models.IntegerField(default=0, verbose_name='Stock Mínimo')),
                ('ubicacion', models.CharField(blank=True, help_text='Ej: Estante A, Cajón 3', max_length=200, verbose_name='Ubicación Física')),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('usado', 'Usado (Operativo)'), ('malo', 'Malo/Para Reparar')], default='nuevo', max_length=50, verbose_name='Estado')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='repuestos/', verbose_name='Imagen')),
                ('especificaciones', models.JSONField(blank=True, default=dict, help_text='Ej: {"voltaje": "24V", "hilo": "1/4 NPT"}', verbose_name='Especificaciones Técnicas')),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Unitario (CLP)')),
                ('proveedor_ultima_compra', models.CharField(blank=True, max_length=200, verbose_name='Proveedor Última Compra')),
                ('fecha_ultima_compra', models.DateField(blank=True, null=True, verbose_name='Fecha Última Compra')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario_app.categoria', verbose_name='Categoría')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repuestos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Repuesto',
                'verbose_name_plural': 'Repuestos',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada (Compra/Devolución)'), ('salida', 'Salida (Uso en terreno)'), ('ajuste', 'Ajuste de Inventario')], max_length=50, verbose_name='Tipo de Movimiento')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario_app.repuesto', verbose_name='Repuesto')),
            ],
            options={
                'verbose_name': 'Movimiento de Stock',
                'verbose_name_plural': 'Movimientos de Stock',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ParametroCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Voltaje, Medida Interior, Capacitancia', max_length=100, verbose_name='Nombre del Parámetro')),
                ('unidad', models.CharField(blank=True, help_text='Ej: V, mm, µF, PSI', max_length=50, verbose_name='Unidad de Medida')),
                ('obligatorio', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros_definidos', to='inventario_app.categoria')),
            ],
            options={
                'verbose_name': 'Parámetro de Categoría',
                'verbose_name_plural': 'Parámetros de Categoría',
                'ordering': ['categoria', 'nombre'],
                'unique_together': {('categoria', 'nombre')},
            },
        ),
    ]
