# Generated by Django 5.0.1 on 2026-09-26 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repuesto',
            name='codigo_interno',
            field=models.CharField(blank=True, help_text='Se genera automáticamente si se deja vacío', max_length=50, unique=True, verbose_name='Código Interno'),
        ),
    ]
