# Generated by Django 5.0.1 on 2026-09-26 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_app', '0002_alter_repuesto_codigo_interno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametrocategoria',
            name='obligatorio',
        ),
        migrations.AlterField(
            model_name='parametrocategoria',
            name='unidad',
            field=models.CharField(blank=True, help_text='Ej: V, mm, µF, PSI, metros', max_length=50, verbose_name='Unidad de Medida'),
        ),
        migrations.CreateModel(
            name='ParametroRepuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Parámetro')),
                ('valor', models.CharField(max_length=200, verbose_name='Valor')),
                ('unidad', models.CharField(blank=True, max_length=50, verbose_name='Unidad de Medida')),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros', to='inventario_app.repuesto')),
            ],
            options={
                'verbose_name': 'Parámetro del Repuesto',
                'verbose_name_plural': 'Parámetros del Repuesto',
                'ordering': ['nombre'],
            },
        ),
    ]
